@NewsApi_HostAddress = http://localhost:5092



###

# Tags Endpoints
GET {{NewsApi_HostAddress}}/tag/
Accept: application/json

###

# Tags Endpoints
GET {{NewsApi_HostAddress}}/category/
Accept: application/json

###


